version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-wanda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: wanda-app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    command: python main.py
